SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_KEY, COLUMN_DEFAULT, EXTRA
FROM INFORMATION_SCHEMA.COLUMNS
TABLE_SCHEMA = 'alx_book_store'", "TABLE_NAME = 'Books'
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'books';